# Generated by Django 5.1.4 on 2025-08-03 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_access_token', models.TextField(verbose_name='encrypted access token')),
                ('_refresh_token', models.TextField(verbose_name='encrypted refresh token')),
                ('token_type', models.CharField(default='Bearer', max_length=50, verbose_name='token type')),
                ('expires_at', models.DateTimeField(verbose_name='token expires at')),
                ('cloud_id', models.CharField(max_length=255, verbose_name='cloud id')),
                ('site_url', models.URLField(verbose_name='site url')),
                ('site_name', models.CharField(max_length=255, verbose_name='site name')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='last sync at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jira_integration', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'jira integration',
                'verbose_name_plural': 'jira integrations',
                'db_table': 'jira_integrations',
            },
        ),
    ]
