# Generated by Django 5.1.4 on 2025-08-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_jiraintegration'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraintegration',
            name='scopes_version',
            field=models.IntegerField(default=1, verbose_name='scopes version'),
        ),
    ]
